
const motivation = {
    1:'“The Best Way To Get Started Is To Quit Talking And Begin Doing.” – Walt Disney',
    2:'“The Pessimist Sees Difficulty In Every Opportunity. The Optimist Sees Opportunity In Every Difficulty.” – Winston Churchill',
    3:'“Don’t Let Yesterday Take Up Too Much Of Today.” – Will Rogers   ',
    4:'“You Learn More From Failure Than From Success. Don’t Let It Stop You. Failure Builds Character.” – Unknown',
    5:'“It’s Not Whether You Get Knocked Down, It’s Whether You Get Up.” – Vince Lombardi',
    6:'“People Who Are Crazy Enough To Think They Can Change The World, Are The Ones Who Do.” – Rob Siltanen',
    7:'“We May Encounter Many Defeats But We Must Not Be Defeated.” – Maya Angelou',
    8:'“Knowing Is Not Enough; We Must Apply. Wishing Is Not Enough; We Must Do.” – Johann Wolfgang Von Goethe',
    9:'“We Generate Fears While We Sit. We Overcome Them By Action.” – Dr. Henry Link',
    10:'“Security Is Mostly A Superstition. Life Is Either A Daring Adventure Or Nothing.” – Life Quote By Helen Keller',
    11:'“The Man Who Has Confidence In Himself Gains The Confidence Of Others.” – Hasidic',
    12:'“Creativity Is Intelligence Having Fun.” – Albert Einstein',
    13:'“Do What You Can With All You Have, Wherever You Are.” – Theodore Roosevelt',
    14:'“You Are Never Too Old To Set Another Goal Or To Dream A New Dream.” – C.S. Lewis',
    15:'“Reading Is To The Mind, As Exercise Is To The Body.” – Brian Tracy',
    16:'“To See What Is Right And Not Do It Is A Lack Of Courage.” – Confucius',
    17:'“Fake It Until You Make It! Act As If You Had All The Confidence You Require Until It Becomes Your Reality.” – Brian Tracy',
    18:'“For Every Reason It’s Not Possible, There Are Hundreds Of People Who Have Faced The Same Circumstances And Succeeded.” – Jack Canfield',
    19:'“Things Work Out Best For Those Who Make The Best Of How Things Work Out.” – Positive Quote By John Wooden',
    20:'“A Room Without Books Is Like A Body Without A Soul.” – Marcus Tullius Cicero',
    21:'“I Think Goals Should Never Be Easy, They Should Force You To Work, Even If They Are Uncomfortable At The Time.” – Michael Phelps',
    22:'“One Of The Lessons That I Grew Up With Was To Always Stay True To Yourself And Never Let What Somebody Else Says Distract You From Your Goals.” – Michelle Obama',
    23:'“Today’s Accomplishments Were Yesterday’s Impossibilities.” – Robert H. Schuller',
    24:'“The Only Way To Do Great Work Is To Love What You Do. If You Haven’t Found It Yet, Keep Looking. Don’t Settle.” – Steve Jobs',
    25:'“You Don’t Have To Be Great To Start, But You Have To Start To Be Great.” – Zig Ziglar',
    26:'“A Clear Vision, Backed By Definite Plans, Gives You A Tremendous Feeling Of Confidence And Personal Power.” – Brian Tracy',
    27:'“There Are No Limits To What You Can Accomplish, Except The Limits You Place On Your Own Thinking.” – Brian Tracy'
    // 4:'nnew4444',
    // 5:'nnew55555',
    // 6:'nnew66666',
    // 1:'nnew1',
    // 2:'nnew22',
    // 3:'nnew333',
    // 4:'nnew4444',
    // 5:'nnew55555',
    // 6:'nnew66666',
    // 1:'nnew1',
    // 2:'nnew22',
    // 3:'nnew333',
    // 4:'nnew4444',
    // 5:'nnew55555',
    // 6:'nnew66666'
    // 1:'nnew1',
    // 2:'nnew22',
    // 3:'nnew333',
    // 4:'nnew4444',
    // 5:'nnew55555',
    // 6:'nnew66666',
    // 1:'nnew1',
    // 2:'nnew22',
    // 3:'nnew333',
    // 4:'nnew4444',
    // 5:'nnew55555',
    // 6:'nnew66666',
    // 1:'nnew1',
    // 2:'nnew22',
    // 3:'nnew333',
    // 4:'nnew4444',
    // 5:'nnew55555',
    // 6:'nnew66666'

}

const inspirational = {

    1:'“Integrity Is The Most Valuable And Respected Quality Of Leadership. Always Keep Your Word.”',
    2:'“Leadership Is The Ability To Get Extraordinary Achievement From Ordinary People”',
    3:'“Leaders Set High Standards. Refuse To Tolerate Mediocrity Or Poor Performance”',
    4:'“Clarity Is The Key To Effective Leadership. What Are Your Goals?”',
    5:'“Leaders Think And Talk About The Solutions. Followers Think And Talk About The Problems.”',
    6:'“The Key Responsibility Of Leadership Is To Think About The Future. No One Else Can Do It For You.”',
    7:'“Leaders Never Use The Word Failure. They Look Upon Setbacks As Learning Experiences.”',
    8:'“Practice Golden Rule Management In Everything You Do. Manage Others The Way You Would Like To Be Managed.”',
    9:'“Superior Leaders Are Willing To Admit A Mistake And Cut Their Losses. Be Willing To Admit That You’ve Changed Your Mind. Don’t Persist When The Original Decision Turns Out To Be A Poor One.”',
    10:'“Leaders Are Anticipatory Thinkers. They Consider All Consequences Of Their Behaviors Before They Act.”',
    11:'“The True Test Of Leadership Is How Well You Function In A Crisis.”',
    12:'“Leaders Concentrate Single-Mindedly On One Thing– The Most Important Thing, And They Stay At It Until It’s Complete.”',
    13:'“The Three ‘C’s’ Of Leadership Are Consideration, Caring, And Courtesy. Be Polite To Everyone.”',
    14:'“Leadership Is More Who You Are Than What You Do.”',
    15:'“Entrepreneurial Leadership Requires The Ability To Move Quickly When Opportunity Presents Itself.”',
    16:'“Leaders Are Innovative, Entrepreneurial, And Future-Oriented. They Focus On Getting The Job Done Well.”',
    17:'“Leaders Are Never Satisfied; They Continually Strive To Be Better.”'
    // 6:'nnew66666',
    // 1:'nnew1',
    // 2:'nnew22',
    // 3:'nnew333',
    // 4:'nnew4444',
    // 5:'nnew55555',
    // 6:'nnew66666',
    // 1:'nnew1',
    // 2:'nnew22',
    // 3:'nnew333',
    // 4:'nnew4444',
    // 5:'nnew55555',
    // 6:'nnew66666'
}


    
module.exports ={
    motivation,
    inspirational
}